package com.example.chinalawtranslate.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.5
 * 2021-10-25T22:00:22.359+08:00
 * Generated source version: 3.2.5
 *
 */
@WebService(targetNamespace = "http://service.chinalawtranslate.example.com/", name = "DocService")
@XmlSeeAlso({ObjectFactory.class})
public interface DocService {

    @WebMethod
    @RequestWrapper(localName = "getByTitle", targetNamespace = "http://service.chinalawtranslate.example.com/", className = "com.example.chinalawtranslate.service.GetByTitle")
    @ResponseWrapper(localName = "getByTitleResponse", targetNamespace = "http://service.chinalawtranslate.example.com/", className = "com.example.chinalawtranslate.service.GetByTitleResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.example.chinalawtranslate.service.Doc getByTitle(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );
}
